# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-nbdev-mkdocs-0-6-0-rc0',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/test-nbdev-mkdocs-0-6-0-rc0',
                'lib_path': 'test_nbdev_mkdocs_0_6_0_rc0'},
  'syms': { 'test_nbdev_mkdocs_0_6_0_rc0.core': { 'test_nbdev_mkdocs_0_6_0_rc0.core.foo': ( 'core.html#foo',
                                                                                            'test_nbdev_mkdocs_0_6_0_rc0/core.py')}}}
