# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['foo', 'Test']

# %% ../nbs/00_core.ipynb 3
def foo(): pass

# %% ../nbs/00_core.ipynb 4
class Test:
    """Test"""
    def instance_method(self):
        """instance_method"""
        return "instance_method"

    @staticmethod
    def static_method():
        """static_method"""
        return "static_method"
